language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
install:
- npm install
before_script:
- chmod -R +x ./ci/
- "./ci/version_control"
script:
- npm run lint
- npm run build
deploy:
  cleanup: false
  provider: script
  script: bash ci/deploy
  on:
    branch: master
    tags: true
