language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - chmod -R +x ./ci/
  - "./ci/version_control"
script:
  - npm run lint
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  on:
    branch: master
    tags: true
