language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - chmod -R +x ./ci/
  - "./ci/version_control"
script:
  - npm run lint
  - npm run build
after_success:
  - firebase use --token $FIREBASE_TOKEN about-me-6a44f
  - firebase --non-interactive --token $FIREBASE_TOKEN
deploy:
  skip_cleanup: true
  provider: firebase
  project: "passrator"
  token:
    secure: "$FIREBASE_TOKEN"
  on:
    branch: master
